import { useEffect, useMemo, useState } from 'react';
import { AlertCircle, ArrowLeft, BarChart3, CheckCircle2, ChevronRight, Clock3, Headphones, LayoutDashboard, LogOut, Menu, MessageSquare, Plus, Search, Send, ShieldCheck, Ticket, UserRound, X } from 'lucide-react';
import { api } from './api';

const statusMeta = { open: ['Terbuka','blue'], onprogress: ['Diproses','amber'], resolved: ['Selesai','green'], rejected: ['Ditolak','red'] };
const priorityMeta = { low: ['Rendah','slate'], medium: ['Sedang','amber'], high: ['Tinggi','red'] };
const fmtDate = value => value ? new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)) : '—';

function Toast({ toast, close }) { if (!toast) return null; return <div className={`toast ${toast.type}`}><span>{toast.type==='error'?<AlertCircle/>:<CheckCircle2/>}</span><p>{toast.message}</p><button onClick={close}><X/></button></div> }
function Badge({ type, value }) { const meta = type==='status'?statusMeta[value]:priorityMeta[value]; return <span className={`badge ${meta?.[1]||'slate'}`}><i/>{meta?.[0]||value}</span> }
function Brand() { return <div className="brand"><span><Ticket/></span><div>Tiketin<small>HELPDESK</small></div></div> }

function Auth({ onAuth, notify }) {
  const [mode,setMode]=useState('login'); const [loading,setLoading]=useState(false); const [form,setForm]=useState({name:'',email:'',password:''});
  const submit=async e=>{e.preventDefault();setLoading(true);try{const res=await api(`/${mode}`,{method:'POST',body:JSON.stringify(form)});localStorage.setItem('ticket_token',res.data.token);onAuth(res.data.user);notify(mode==='login'?'Selamat datang kembali!':'Akun berhasil dibuat.');}catch(err){notify(err.message,'error')}finally{setLoading(false)}};
  return <main className="auth-page"><section className="auth-story"><Brand/><div className="story-copy"><span className="eyebrow">LAYANAN DUKUNGAN TERPADU</span><h1>Masalah datang.<br/><em>Solusi menyusul.</em></h1><p>Sampaikan kendala Anda dengan mudah. Tim kami akan membantu sampai benar-benar selesai.</p><div className="promise"><span><Clock3/></span><div><b>Respons yang jelas</b><small>Pantau setiap progres secara transparan</small></div></div></div><p className="copyright">© 2026 Tiketin. Dibuat untuk pelayanan yang lebih baik.</p></section><section className="auth-form"><div className="mobile-brand"><Brand/></div><div className="form-card"><span className="eyebrow">{mode==='login'?'SELAMAT DATANG':'MULAI SEKARANG'}</span><h2>{mode==='login'?'Masuk ke akun Anda':'Buat akun baru'}</h2><p>{mode==='login'?'Kelola dan pantau tiket dukungan Anda.':'Laporkan kendala dan dapatkan bantuan.'}</p><form onSubmit={submit}>{mode==='register'&&<label>Nama lengkap<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Nama Anda"/></label>}<label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="nama@email.com"/></label><label>Kata sandi<input required minLength="6" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="Minimal 6 karakter"/></label><button className="primary wide" disabled={loading}>{loading?'Mohon tunggu...':mode==='login'?'Masuk ke Tiketin':'Daftar sekarang'}<ChevronRight/></button></form><div className="switch">{mode==='login'?'Belum punya akun?':'Sudah punya akun?'} <button onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Daftar gratis':'Masuk'}</button></div></div></section></main>
}

function Sidebar({page,setPage,user,logout,open,setOpen}) { return <><div className={`sidebar-overlay ${open?'show':''}`} onClick={()=>setOpen(false)}/><aside className={`sidebar ${open?'open':''}`}><Brand/><button className="sidebar-close" onClick={()=>setOpen(false)}><X/></button><nav><small>MENU UTAMA</small><button className={page==='dashboard'?'active':''} onClick={()=>{setPage('dashboard');setOpen(false)}}><LayoutDashboard/>Ringkasan</button><button className={page==='tickets'?'active':''} onClick={()=>{setPage('tickets');setOpen(false)}}><Ticket/>Semua Tiket</button><button className={page==='create'?'active':''} onClick={()=>{setPage('create');setOpen(false)}}><Plus/>Buat Tiket</button></nav><div className="sidebar-foot"><div className="profile"><span>{user.name?.[0]}</span><div><b>{user.name}</b><small>{user.role==='admin'?'Administrator':'Pengguna'}</small></div></div><button className="logout" onClick={logout}><LogOut/>Keluar</button></div></aside></> }

function Dashboard({stats,tickets,user,setPage,setSelected}) { const dist=stats?.status_distribution||{}; return <><header className="page-head"><div><span className="eyebrow">RINGKASAN HARI INI</span><h1>Halo, {user.name?.split(' ')[0]} <span>👋</span></h1><p>Berikut perkembangan layanan dukungan Anda.</p></div><button className="primary" onClick={()=>setPage('create')}><Plus/>Buat Tiket Baru</button></header><section className="stats-grid"><Stat icon={<Ticket/>} label="Total tiket bulan ini" value={stats?.total_tickets??0} color="navy"/><Stat icon={<Clock3/>} label="Tiket masih aktif" value={stats?.active_tickets??0} color="amber"/><Stat icon={<CheckCircle2/>} label="Tiket terselesaikan" value={stats?.resolved_tickets??0} color="green"/><Stat icon={<BarChart3/>} label="Rata-rata penyelesaian" value={`${stats?.avg_resolution_time??0} jam`} color="blue"/></section><section className="dashboard-grid"><div className="panel"><div className="panel-head"><div><h3>Tiket terbaru</h3><p>Aktivitas dukungan terkini</p></div><button onClick={()=>setPage('tickets')}>Lihat semua <ChevronRight/></button></div><div className="ticket-list">{tickets.slice(0,4).map(t=><button className="ticket-row" key={t.id} onClick={()=>setSelected(t.code)}><div className="ticket-icon"><MessageSquare/></div><div className="ticket-main"><b>{t.title}</b><small>{t.code} · {fmtDate(t.created_at)}</small></div><Badge type="status" value={t.status}/><ChevronRight/></button>)}{!tickets.length&&<Empty small/>}</div></div><div className="panel distribution"><div className="panel-head"><div><h3>Status tiket</h3><p>Distribusi bulan ini</p></div></div>{Object.entries(statusMeta).map(([key,m])=>{const total=stats?.total_tickets||1;return <div className="dist-row" key={key}><div><span>{m[0]}</span><b>{dist[key]||0}</b></div><div className="bar"><i className={m[1]} style={{width:`${((dist[key]||0)/total)*100}%`}}/></div></div>})}</div></section></> }
function Stat({icon,label,value,color}) { return <div className="stat-card"><span className={`stat-icon ${color}`}>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></div> }
function Empty({small=false}) { return <div className={`empty ${small?'small':''}`}><span><Ticket/></span><b>Belum ada tiket</b><p>Buat tiket pertama untuk mendapatkan bantuan.</p></div> }

function Tickets({tickets,setSelected,setPage}) { const [search,setSearch]=useState(''); const [status,setStatus]=useState(''); const filtered=useMemo(()=>tickets.filter(t=>(!search||`${t.code} ${t.title}`.toLowerCase().includes(search.toLowerCase()))&&(!status||t.status===status)),[tickets,search,status]); return <><header className="page-head compact"><div><span className="eyebrow">PUSAT DUKUNGAN</span><h1>Semua Tiket</h1><p>Temukan dan pantau seluruh laporan dukungan.</p></div><button className="primary" onClick={()=>setPage('create')}><Plus/>Buat Tiket</button></header><section className="panel tickets-panel"><div className="filters"><label className="search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari kode atau judul tiket..."/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Semua status</option>{Object.entries(statusMeta).map(([k,v])=><option key={k} value={k}>{v[0]}</option>)}</select></div><div className="table"><div className="tr th"><span>TIKET</span><span>PRIORITAS</span><span>STATUS</span><span>DIBUAT</span><span/></div>{filtered.map(t=><button className="tr" key={t.id} onClick={()=>setSelected(t.code)}><span className="title-cell"><b>{t.title}</b><small>{t.code}</small></span><span><Badge type="priority" value={t.priority}/></span><span><Badge type="status" value={t.status}/></span><span className="date-cell">{fmtDate(t.created_at)}</span><ChevronRight/></button>)}</div>{!filtered.length&&<Empty/>}</section></> }

function CreateTicket({back,reload,notify}) { const [form,setForm]=useState({title:'',description:'',priority:'medium'}); const [loading,setLoading]=useState(false); const submit=async e=>{e.preventDefault();setLoading(true);try{await api('/ticket',{method:'POST',body:JSON.stringify(form)});notify('Tiket berhasil dibuat.');await reload();back();}catch(err){notify(err.message,'error')}finally{setLoading(false)}};return <><header className="page-head compact"><div><button className="back" onClick={back}><ArrowLeft/>Kembali</button><h1>Buat Tiket Baru</h1><p>Ceritakan kendala Anda selengkap mungkin agar kami dapat membantu lebih cepat.</p></div></header><section className="panel form-panel"><form onSubmit={submit}><label>Judul kendala <span>*</span><input required maxLength="255" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Contoh: Tidak dapat mengakses halaman pembayaran"/></label><label>Prioritas <span>*</span><div className="priority-options">{Object.entries(priorityMeta).map(([k,v])=><button type="button" className={form.priority===k?'selected':''} key={k} onClick={()=>setForm({...form,priority:k})}><i className={v[1]}/><b>{v[0]}</b><small>{k==='low'?'Tidak mendesak':k==='medium'?'Perlu segera ditangani':'Menghambat pekerjaan'}</small></button>)}</div></label><label>Deskripsi kendala <span>*</span><textarea required rows="8" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Jelaskan apa yang terjadi, kapan mulai terjadi, dan langkah yang sudah Anda coba..."/></label><div className="form-actions"><button type="button" className="secondary" onClick={back}>Batal</button><button className="primary" disabled={loading}>{loading?'Mengirim...':'Kirim Tiket'}<Send/></button></div></form></section></> }

function TicketDetail({code,back,user,notify,reload}) { const [ticket,setTicket]=useState(null); const [content,setContent]=useState(''); const [status,setStatus]=useState('onprogress'); const [loading,setLoading]=useState(false); const load=()=>api(`/ticket/${code}`).then(r=>{setTicket(r.data);setStatus(r.data.status)}).catch(e=>notify(e.message,'error')); useEffect(load,[code]); const send=async e=>{e.preventDefault();setLoading(true);try{await api(`/ticket-reply/${code}`,{method:'POST',body:JSON.stringify({content,...(user.role==='admin'?{status}:{})})});setContent('');notify('Balasan berhasil dikirim.');await load();await reload();}catch(err){notify(err.message,'error')}finally{setLoading(false)}};if(!ticket)return <div className="loading">Memuat tiket...</div>;return <><header className="page-head compact detail-head"><div><button className="back" onClick={back}><ArrowLeft/>Kembali ke tiket</button><div className="detail-title"><span className="ticket-icon"><Ticket/></span><div><small>{ticket.code}</small><h1>{ticket.title}</h1></div></div></div><div className="detail-badges"><Badge type="priority" value={ticket.priority}/><Badge type="status" value={ticket.status}/></div></header><section className="detail-grid"><div className="conversation"><article className="message original"><div className="avatar">{ticket.user?.name?.[0]}</div><div><div className="message-head"><b>{ticket.user?.name}</b><span>{fmtDate(ticket.created_at)}</span></div><p>{ticket.description}</p></div></article>{ticket.ticket_replies?.map(r=><article className={`message ${r.user?.role==='admin'?'admin':''}`} key={r.id}><div className="avatar">{r.user?.role==='admin'?<ShieldCheck/>:r.user?.name?.[0]}</div><div><div className="message-head"><b>{r.user?.name}{r.user?.role==='admin'&&<em>Tim Dukungan</em>}</b><span>{fmtDate(r.created_at)}</span></div><p>{r.content}</p></div></article>)}<form className="reply-box" onSubmit={send}><textarea required value={content} onChange={e=>setContent(e.target.value)} placeholder="Tulis balasan Anda..." rows="4"/>{user.role==='admin'&&<div className="reply-status"><label>Ubah status<select value={status} onChange={e=>setStatus(e.target.value)}>{Object.entries(statusMeta).map(([k,v])=><option key={k} value={k}>{v[0]}</option>)}</select></label></div>}<button className="primary" disabled={loading}>{loading?'Mengirim...':'Kirim Balasan'}<Send/></button></form></div><aside className="ticket-info panel"><h3>Informasi tiket</h3><dl><div><dt><UserRound/>Pelapor</dt><dd>{ticket.user?.name}<small>{ticket.user?.email}</small></dd></div><div><dt><Clock3/>Dibuat</dt><dd>{fmtDate(ticket.created_at)}</dd></div><div><dt><MessageSquare/>Balasan</dt><dd>{ticket.ticket_replies?.length||0} pesan</dd></div></dl></aside></section></> }

export default function App(){const [user,setUser]=useState(null),[page,setPage]=useState('dashboard'),[tickets,setTickets]=useState([]),[stats,setStats]=useState(null),[selected,setSelected]=useState(null),[toast,setToast]=useState(null),[menu,setMenu]=useState(false),[checking,setChecking]=useState(true);const notify=(message,type='success')=>{setToast({message,type});setTimeout(()=>setToast(null),3500)};const load=async()=>{try{const [t,s]=await Promise.all([api('/ticket'),api('/dashboard/statistics')]);setTickets(t.data||[]);setStats(s.data)}catch(e){notify(e.message,'error')}};useEffect(()=>{const token=localStorage.getItem('ticket_token');if(!token){setChecking(false);return}api('/me').then(r=>{setUser(r.data);load()}).catch(()=>localStorage.removeItem('ticket_token')).finally(()=>setChecking(false))},[]);useEffect(()=>{if(user)load()},[user]);const logout=async()=>{try{await api('/logout',{method:'POST'})}catch{}localStorage.removeItem('ticket_token');setUser(null)};if(checking)return <div className="splash"><Brand/><span/></div>;if(!user)return <><Auth onAuth={setUser} notify={notify}/><Toast toast={toast} close={()=>setToast(null)}/></>;return <div className="app-shell"><Sidebar page={page} setPage={p=>{setSelected(null);setPage(p)}} user={user} logout={logout} open={menu} setOpen={setMenu}/><main className="content"><div className="mobile-top"><button onClick={()=>setMenu(true)}><Menu/></button><Brand/><span className="mini-avatar">{user.name?.[0]}</span></div>{selected?<TicketDetail code={selected} user={user} back={()=>setSelected(null)} notify={notify} reload={load}/>:page==='dashboard'?<Dashboard stats={stats} tickets={tickets} user={user} setPage={setPage} setSelected={setSelected}/>:page==='tickets'?<Tickets tickets={tickets} setSelected={setSelected} setPage={setPage}/>:<CreateTicket back={()=>setPage('tickets')} reload={load} notify={notify}/>}</main><Toast toast={toast} close={()=>setToast(null)}/></div>}
